// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231104231318_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LengthInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "Togo",
                            Director = "Theresa Bergnaum",
                            Genre = "Electronics",
                            LengthInMinutes = 196,
                            ReleaseDate = new DateTime(2011, 9, 10, 0, 58, 37, 191, DateTimeKind.Local).AddTicks(6788),
                            Title = "Practical Metal Computer"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "Uzbekistan",
                            Director = "Doug Conroy",
                            Genre = "Electronics",
                            LengthInMinutes = 33,
                            ReleaseDate = new DateTime(2018, 7, 7, 21, 30, 48, 860, DateTimeKind.Local).AddTicks(4685),
                            Title = "Small Cotton Chair"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Samoa",
                            Director = "Frank Tillman",
                            Genre = "Outdoors",
                            LengthInMinutes = 177,
                            ReleaseDate = new DateTime(1994, 10, 16, 13, 8, 37, 161, DateTimeKind.Local).AddTicks(6045),
                            Title = "Incredible Metal Sausages"
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "Palau",
                            Director = "Alison Strosin",
                            Genre = "Outdoors",
                            LengthInMinutes = 137,
                            ReleaseDate = new DateTime(2017, 10, 15, 17, 17, 31, 407, DateTimeKind.Local).AddTicks(3181),
                            Title = "Intelligent Granite Salad"
                        },
                        new
                        {
                            Id = 5,
                            CountryOfOrigin = "Heard Island and McDonald Islands",
                            Director = "Annette Kerluke",
                            Genre = "Outdoors",
                            LengthInMinutes = 211,
                            ReleaseDate = new DateTime(2000, 10, 26, 6, 18, 33, 475, DateTimeKind.Local).AddTicks(4026),
                            Title = "Sleek Steel Bacon"
                        },
                        new
                        {
                            Id = 6,
                            CountryOfOrigin = "Uruguay",
                            Director = "Russell Nienow",
                            Genre = "Shoes",
                            LengthInMinutes = 60,
                            ReleaseDate = new DateTime(1996, 8, 16, 8, 44, 19, 413, DateTimeKind.Local).AddTicks(1442),
                            Title = "Rustic Rubber Mouse"
                        },
                        new
                        {
                            Id = 7,
                            CountryOfOrigin = "Nicaragua",
                            Director = "Marsha O'Kon",
                            Genre = "Computers",
                            LengthInMinutes = 58,
                            ReleaseDate = new DateTime(2012, 4, 30, 13, 0, 27, 123, DateTimeKind.Local).AddTicks(5360),
                            Title = "Gorgeous Metal Hat"
                        },
                        new
                        {
                            Id = 8,
                            CountryOfOrigin = "Guadeloupe",
                            Director = "Desiree Von",
                            Genre = "Clothing",
                            LengthInMinutes = 57,
                            ReleaseDate = new DateTime(2013, 2, 28, 4, 55, 34, 451, DateTimeKind.Local).AddTicks(3370),
                            Title = "Fantastic Concrete Keyboard"
                        },
                        new
                        {
                            Id = 9,
                            CountryOfOrigin = "Kuwait",
                            Director = "Renee Kuhn",
                            Genre = "Books",
                            LengthInMinutes = 198,
                            ReleaseDate = new DateTime(2007, 12, 22, 11, 28, 15, 687, DateTimeKind.Local).AddTicks(1814),
                            Title = "Generic Concrete Chicken"
                        },
                        new
                        {
                            Id = 10,
                            CountryOfOrigin = "Sao Tome and Principe",
                            Director = "Harriet Kuhn",
                            Genre = "Kids",
                            LengthInMinutes = 227,
                            ReleaseDate = new DateTime(2011, 3, 4, 3, 40, 1, 94, DateTimeKind.Local).AddTicks(5910),
                            Title = "Awesome Plastic Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
