// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231119204836_rozszerzenie-modelu")]
    partial class rozszerzeniemodelu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("LengthInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "Dania",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Director = "Władysław Stępień",
                            LengthInMinutes = 211,
                            ReleaseDate = new DateTime(2009, 4, 16, 6, 8, 34, 680, DateTimeKind.Local).AddTicks(9747),
                            Title = "Ergonomic Steel Pants"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "Kiribati",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Director = "Jakub Nowaczyk",
                            LengthInMinutes = 115,
                            ReleaseDate = new DateTime(2009, 3, 8, 22, 0, 40, 3, DateTimeKind.Local).AddTicks(1249),
                            Title = "Intelligent Metal Chips"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Gujana",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Director = "Regina Robak",
                            LengthInMinutes = 156,
                            ReleaseDate = new DateTime(1994, 3, 21, 17, 36, 33, 16, DateTimeKind.Local).AddTicks(703),
                            Title = "Rustic Rubber Sausages"
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "Trynidad i Tobago",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Director = "Łazarz Pawlikowski",
                            LengthInMinutes = 209,
                            ReleaseDate = new DateTime(2000, 9, 5, 5, 39, 30, 272, DateTimeKind.Local).AddTicks(7053),
                            Title = "Fantastic Wooden Chips"
                        },
                        new
                        {
                            Id = 5,
                            CountryOfOrigin = "Republika Środkowoafrykańska",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Director = "Wawrzyniec Szczepański",
                            LengthInMinutes = 220,
                            ReleaseDate = new DateTime(2002, 12, 31, 23, 25, 34, 859, DateTimeKind.Local).AddTicks(4326),
                            Title = "Tasty Fresh Chips"
                        },
                        new
                        {
                            Id = 6,
                            CountryOfOrigin = "Liberia",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Director = "Laura Cygan",
                            LengthInMinutes = 102,
                            ReleaseDate = new DateTime(2015, 10, 17, 10, 28, 37, 170, DateTimeKind.Local).AddTicks(6541),
                            Title = "Incredible Cotton Keyboard"
                        },
                        new
                        {
                            Id = 7,
                            CountryOfOrigin = "Kenia",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Director = "Józef Broda",
                            LengthInMinutes = 171,
                            ReleaseDate = new DateTime(2004, 1, 18, 14, 44, 19, 137, DateTimeKind.Local).AddTicks(2069),
                            Title = "Small Wooden Shirt"
                        },
                        new
                        {
                            Id = 8,
                            CountryOfOrigin = "Uganda",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Director = "Marceli Żurek",
                            LengthInMinutes = 88,
                            ReleaseDate = new DateTime(2021, 9, 9, 16, 21, 59, 995, DateTimeKind.Local).AddTicks(1687),
                            Title = "Handmade Metal Towels"
                        },
                        new
                        {
                            Id = 9,
                            CountryOfOrigin = "Mongolia",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Director = "Cyrus Nowaczyk",
                            LengthInMinutes = 29,
                            ReleaseDate = new DateTime(2000, 9, 18, 17, 18, 57, 196, DateTimeKind.Local).AddTicks(8242),
                            Title = "Refined Soft Tuna"
                        },
                        new
                        {
                            Id = 10,
                            CountryOfOrigin = "Kenia",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Director = "Rajnold Stefaniak",
                            LengthInMinutes = 180,
                            ReleaseDate = new DateTime(1998, 3, 5, 7, 23, 50, 472, DateTimeKind.Local).AddTicks(8645),
                            Title = "Refined Cotton Bacon"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.MovieActors", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Review", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Movie", b =>
                {
                    b.HasOne("P06Shop.Shared.MovieCollection.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.MovieActors", b =>
                {
                    b.HasOne("P06Shop.Shared.MovieCollection.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P06Shop.Shared.MovieCollection.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Review", b =>
                {
                    b.HasOne("P06Shop.Shared.MovieCollection.Movie", "Movie")
                        .WithOne("Review")
                        .HasForeignKey("P06Shop.Shared.MovieCollection.Review", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("P06Shop.Shared.MovieCollection.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
